configs:
  config.json:
    content: |
      {
        "verifier_instances": [
          "http://vlei-verifier-1:7676",
          "http://vlei-verifier-2:7676",
          "http://vlei-verifier-3:7676"
        ]
      }
  keria.json:
    content: |
      {
            "dt": "2023-12-01T10:05:25.062609+00:00",
            "keria": {
              "dt": "2023-12-01T10:05:25.062609+00:00",
              "curls": ["http://keria:3902/"]
            },
            "iurls": [
              "http://witness-demo:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller",
              "http://witness-demo:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller",
              "http://witness-demo:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller",
              "http://witness-demo:5645/oobi/BM35JN8XeJSEfpxopjn5jr7tAHCE5749f0OobhMLCorE/controller",
              "http://witness-demo:5646/oobi/BIj15u5V11bkbtAxMA7gcNJZcax-7TgaBMLsQnMHpYHP/controller",
              "http://witness-demo:5647/oobi/BF2rZTW79z4IXocYRQnjjsOuvFUQv-ptCf8Yltd7PfsM/controller"
            ]
      }

  wan.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wan": {
            "dt": "2022-01-20T12:57:59.823350+00:00",
            "curls": ["tcp://witness-demo:5632/", "http://witness-demo:5642/"]
          },
      }

  wil.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wil": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5643/"]
          }
      }
  wes.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wes": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5644/"]
          }
      }

  wit.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wit": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5645/"]
          }
      }

  wub.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wub": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5646/"]
          }
      }

  wyx.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wyx": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5647/"]
          }
      }

services:
  vlei-verifier-router:
    image: gleif/vlei-verifier-router:latest
    configs:
      - source: config.json
        target: /usr/local/var/server/config.json
    depends_on:
      - redis
      - vlei-verifier-1
      - vlei-verifier-2
      - vlei-verifier-3
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 7676:7676
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7676/health
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  vlei-server:
    image: gleif/vlei
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    command:
      - vLEI-server
      - -s
      - ./schema/acdc
      - -c
      - ./samples/acdc/
      - -o
      - ./samples/oobis/
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 7723:7723

  keria:
    depends_on:
      vlei-server:
        condition: service_healthy
      witness-demo:
        condition: service_healthy
    image: ${KERIA_IMAGE:-weboftrust/keria}:${KERIA_IMAGE_TAG:-0.2.0-dev3}
    platform: linux/x86_64
    environment:
      - KERI_AGENT_CORS=1
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - KERI_URL=http://keria:3902
    configs:
      - source: keria.json
        target: /usr/local/var/keri/cf/keria.json
    entrypoint: ['keria', 'start', '--config-file', 'keria', '--name', 'agent']
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://keria:3902/spec.yaml']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5642/oobi']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    configs:
      - source: wan.json
        target: /keripy/scripts/keri/cf/main/wan.json
      - source: wes.json
        target: /keripy/scripts/keri/cf/main/wes.json
      - source: wil.json
        target: /keripy/scripts/keri/cf/main/wil.json
      - source: wit.json
        target: /keripy/scripts/keri/cf/main/wit.json
      - source: wub.json
        target: /keripy/scripts/keri/cf/main/wub.json
      - source: wyx.json
        target: /keripy/scripts/keri/cf/main/wyx.json

  vlei-verifier-1:
    image: gleif/vlei-verifier:latest
    container_name: vlei-verifier-1
    environment:
      - VERIFIER_CONFIG_FILE=verifier-config-test.json
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 5652:7676
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:7676/health']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  vlei-verifier-2:
    image: gleif/vlei-verifier:latest
    container_name: vlei-verifier-2
    environment:
      - VERIFIER_CONFIG_FILE=verifier-config-test.json
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 5653:7676
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:7676/health']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  vlei-verifier-3:
    image: gleif/vlei-verifier:latest
    container_name: vlei-verifier-3
    environment:
      - VERIFIER_CONFIG_FILE=verifier-config-test.json
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 5654:7676
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:7676/health']
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

volumes:
  redis_data:
