name: Multisig Single-User, Non-Delegated AIDs Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**' # Run Validate Build on all PR branches
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test-single-aid-multisig-non-delegated-aids:
    name: Run multisig single-user, non-delegated aids test using keria:${{ matrix.keria-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        keria-version: ['0.2.0-dev3']
        node-version: ['20']
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci

      - name: Run docker
        run: |
          docker pull weboftrust/keria:${{ matrix.keria-version }}
          # docker compose down -v
          # docker compose up verify -d --pull always

      - name: Build
        run: npm run build

      - name: Run workflow
        run: SPEED=fast WORKFLOW=multisig-single-user-non-delegated-aids.yaml CONFIGURATION=configuration-multisig-single-user-non-delegated-aids.json npx jest ./run-workflow.test.ts --runInBand --detectOpenHandles --forceExit
